# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddDrone.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import uic, QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator
from PyQt5.QtWidgets import (QApplication, QWidget, QLabel, QTableView, QTableWidgetItem)
import mysql.connector

class Add_Drone(object):
    def setupDroneID(self):
        cnx = mysql.connector.connect(user='root', password='Fl1ght413612!',
                              host='127.0.0.1',
                              database='restaurant_supply_express', port=3306)
        mycursor = cnx.cursor()
        mycursor.execute("select id from delivery_services")
        myresult = mycursor.fetchall()
        for row_data in myresult:
            for data in row_data:
                self.DroneID.addItem(data)
        cnx.close

    def setupPilots(self):
        cnx = mysql.connector.connect(user='root', password='Fl1ght413612!',
                              host='127.0.0.1',
                              database='restaurant_supply_express', port=3306)
        mycursor = cnx.cursor()
        mycursor.execute("select username from work_for where (username in (select username from pilots) and id = \'" + self.DroneID.currentText() +"\');")
        myresult = mycursor.fetchall()
        for row_data in myresult:
            for data in row_data:
                self.PilotUsername.addItem(data)
        cnx.close

    def changePilots(self):
        self.PilotUsername.clear()
        self.setupPilots()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(576, 469)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(200, -40, 181, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 170, 71, 21))
        self.label_3.setObjectName("label_3")
        self.FuelEntry = QtWidgets.QLineEdit(Form)
        self.FuelEntry.setGeometry(QtCore.QRect(90, 170, 401, 22))
        self.FuelEntry.setText("")
        self.FuelEntry.setObjectName("FuelEntry")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 71, 31))
        self.label_5.setObjectName("label_5")
        self.CapacityEntry = QtWidgets.QLineEdit(Form)
        self.CapacityEntry.setGeometry(QtCore.QRect(90, 210, 401, 22))
        self.CapacityEntry.setObjectName("CapacityEntry")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 290, 61, 31))
        self.label_6.setObjectName("label_6")
        self.addDrone = QtWidgets.QPushButton(Form)
        self.addDrone.setGeometry(QtCore.QRect(230, 380, 93, 28))
        self.addDrone.setObjectName("addDrone")
        self.PilotUsername = QtWidgets.QComboBox(Form)
        self.PilotUsername.setGeometry(QtCore.QRect(90, 300, 401, 22))
        self.PilotUsername.setObjectName("PilotUsername")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 61, 16))
        self.label_4.setObjectName("label_4")
        self.SalesEntry = QtWidgets.QLineEdit(Form)
        self.SalesEntry.setGeometry(QtCore.QRect(90, 250, 401, 22))
        self.SalesEntry.setText("")
        self.SalesEntry.setObjectName("SalesEntry")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(20, 250, 71, 21))
        self.label_7.setObjectName("label_7")
        self.DroneTagEntry = QtWidgets.QLineEdit(Form)
        self.DroneTagEntry.setGeometry(QtCore.QRect(90, 120, 401, 22))
        self.DroneTagEntry.setObjectName("DroneTagEntry")
        self.DroneID = QtWidgets.QComboBox(Form)
        self.DroneID.setGeometry(QtCore.QRect(90, 70, 401, 22))
        self.DroneID.setObjectName("DroneID")
        self.CapacityEntry.setValidator(QIntValidator())
        self.FuelEntry.setValidator(QIntValidator())
        self.SalesEntry.setValidator(QIntValidator())
        self.DroneTagEntry.setValidator(QIntValidator())
        self.setupDroneID()
        self.setupPilots()
        self.DroneID.currentIndexChanged.connect(self.changePilots)
        self.addDrone.clicked.connect(self.add_Drone)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Add a Drone"))
        self.label_3.setText(_translate("Form", "Fuel"))
        self.label_5.setText(_translate("Form", "Capacity"))
        self.label_6.setText(_translate("Form", "Pilot \n"
"Username"))
        self.addDrone.setText(_translate("Form", "Add Drone"))
        self.label_2.setText(_translate("Form", "Drone ID"))
        self.label_4.setText(_translate("Form", "Drone Tag"))
        self.label_7.setText(_translate("Form", "Sales"))

    def add_Drone(self):
        if (len(self.CapacityEntry.text()) > 0 and len(self.DroneTagEntry.text()) > 0 and len(self.FuelEntry.text()) > 0 and len(self.SalesEntry.text()) > 0):
            cnx = mysql.connector.connect(user='root', password='(placeholder)',
                              host='127.0.0.1',
                              database='restaurant_supply_express', port=3306)
            cursor = cnx.cursor()
            cursor.callproc('add_drone', [self.DroneID.currentText(), self.DroneTagEntry.text(), self.FuelEntry.text(), self.CapacityEntry.text(), self.SalesEntry.text(), self.PilotUsername.currentText()])
            cnx.commit()
            cnx.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Add_Drone()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
