# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddEmployee.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import uic, QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator
from PyQt5.QtWidgets import (QApplication, QWidget, QLabel, QTableView, QTableWidgetItem)
import mysql.connector


class Add_NewEmployee(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1026, 410)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(410, -40, 231, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.UsernameEntry = QtWidgets.QLineEdit(Form)
        self.UsernameEntry.setGeometry(QtCore.QRect(100, 90, 401, 22))
        self.UsernameEntry.setObjectName("UsernameEntry")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 61, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 71, 21))
        self.label_3.setObjectName("label_3")
        self.FirstNameEntry = QtWidgets.QLineEdit(Form)
        self.FirstNameEntry.setGeometry(QtCore.QRect(100, 130, 401, 22))
        self.FirstNameEntry.setObjectName("FirstNameEntry")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 61, 21))
        self.label_4.setObjectName("label_4")
        self.LastNameEntry = QtWidgets.QLineEdit(Form)
        self.LastNameEntry.setGeometry(QtCore.QRect(100, 170, 401, 22))
        self.LastNameEntry.setObjectName("LastNameEntry")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 220, 61, 21))
        self.label_5.setObjectName("label_5")
        self.AddressEntry = QtWidgets.QLineEdit(Form)
        self.AddressEntry.setGeometry(QtCore.QRect(100, 220, 401, 22))
        self.AddressEntry.setObjectName("AddressEntry")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 260, 61, 21))
        self.label_6.setObjectName("label_6")
        self.DateEntry = QtWidgets.QDateEdit(Form)
        self.DateEntry.setGeometry(QtCore.QRect(100, 260, 401, 22))
        self.DateEntry.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DateEntry.setCalendarPopup(True)
        self.DateEntry.setObjectName("DateEntry")
        self.addEmployee = QtWidgets.QPushButton(Form)
        self.addEmployee.setGeometry(QtCore.QRect(470, 350, 101, 28))
        self.addEmployee.setObjectName("addEmployee")
        self.TaxIDEntry = QtWidgets.QLineEdit(Form)
        self.TaxIDEntry.setGeometry(QtCore.QRect(600, 90, 401, 22))
        self.TaxIDEntry.setObjectName("TaxIDEntry")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(530, 90, 55, 16))
        self.label_7.setObjectName("label_7")
        self.HireDateEntry = QtWidgets.QDateEdit(Form)
        self.HireDateEntry.setGeometry(QtCore.QRect(600, 260, 401, 22))
        self.HireDateEntry.setCalendarPopup(True)
        self.HireDateEntry.setObjectName("HireDateEntry")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(530, 260, 55, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(530, 130, 51, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(530, 180, 55, 16))
        self.label_10.setObjectName("label_10")
        self.ExperienceEntry = QtWidgets.QLineEdit(Form)
        self.ExperienceEntry.setGeometry(QtCore.QRect(600, 130, 401, 22))
        self.ExperienceEntry.setObjectName("ExperienceEntry")
        self.ExperienceEntry.setValidator(QIntValidator())
        self.SalaryEntry = QtWidgets.QLineEdit(Form)
        self.SalaryEntry.setGeometry(QtCore.QRect(600, 180, 401, 22))
        self.SalaryEntry.setObjectName("SalaryEntry")
        self.SalaryEntry.setValidator(QIntValidator())
        self.addEmployee.clicked.connect(self.addnewEmployee)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Add an Employee"))
        self.label_2.setText(_translate("Form", "Username"))
        self.label_3.setText(_translate("Form", "First Name"))
        self.label_4.setText(_translate("Form", "Last Name"))
        self.label_5.setText(_translate("Form", "Address"))
        self.label_6.setText(_translate("Form", "Birth Date"))
        self.DateEntry.setDisplayFormat(_translate("Form", "yyyy-MM-dd"))
        self.addEmployee.setText(_translate("Form", "Add Employee"))
        self.label_7.setText(_translate("Form", "TaxID"))
        self.HireDateEntry.setDisplayFormat(_translate("Form", "yyyy-MM-dd"))
        self.label_8.setText(_translate("Form", "Hire Date"))
        self.label_9.setText(_translate("Form", "Months \n"
"Worked"))
        self.label_10.setText(_translate("Form", "Salary"))

    def addnewEmployee(self):
        if (len(self.UsernameEntry.text()) > 0 and len(self.UsernameEntry.text()) <= 40 and len(self.FirstNameEntry.text()) > 0 and len(self.FirstNameEntry.text()) <= 100 and len(self.LastNameEntry.text()) > 0 and len(self.LastNameEntry.text()) <= 100 and len(self.AddressEntry.text()) > 0 and len(self.AddressEntry.text()) <= 500 and len(self.TaxIDEntry.text()) > 0 and len(self.TaxIDEntry.text()) <= 40 and len(self.ExperienceEntry.text()) > 0 and len(self.SalaryEntry.text()) > 0):
            cnx = mysql.connector.connect(user='root', password='(placeholder)',
                              host='127.0.0.1',
                              database='restaurant_supply_express', port=3306)
            cursor = cnx.cursor()
            cursor.callproc('add_employee', [self.UsernameEntry.text(), self.FirstNameEntry.text(), self.LastNameEntry.text(), self.AddressEntry.text(), self.DateEntry.text(), self.TaxIDEntry.text(), self.HireDateEntry.text(), int(self.ExperienceEntry.text()), int(self.SalaryEntry.text())])
            cnx.commit()
            cnx.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Add_NewEmployee()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
