# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addLocation.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import uic, QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator
from PyQt5.QtWidgets import (QApplication, QWidget, QLabel, QTableView, QTableWidgetItem)
import mysql.connector


class Add_NewLocation(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(541, 320)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, -40, 181, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.LabelEntry = QtWidgets.QLineEdit(Form)
        self.LabelEntry.setGeometry(QtCore.QRect(100, 90, 401, 22))
        self.LabelEntry.setObjectName("LabelEntry")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 61, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 81, 21))
        self.label_3.setObjectName("label_3")
        self.XCoordEntry = QtWidgets.QLineEdit(Form)
        self.XCoordEntry.setGeometry(QtCore.QRect(100, 130, 401, 22))
        self.XCoordEntry.setObjectName("XCoordEntry")
        self.XCoordEntry.setValidator(QIntValidator())
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 81, 21))
        self.label_4.setObjectName("label_4")
        self.YcoordEntry = QtWidgets.QLineEdit(Form)
        self.YcoordEntry.setGeometry(QtCore.QRect(100, 170, 401, 22))
        self.YcoordEntry.setObjectName("YcoordEntry")
        self.YcoordEntry.setValidator(QIntValidator())
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 220, 61, 21))
        self.label_5.setObjectName("label_5")
        self.SpaceEntry = QtWidgets.QLineEdit(Form)
        self.SpaceEntry.setGeometry(QtCore.QRect(100, 220, 401, 22))
        self.SpaceEntry.setObjectName("SpaceEntry")
        self.SpaceEntry.setValidator(QIntValidator())
        self.addLocation = QtWidgets.QPushButton(Form)
        self.addLocation.setGeometry(QtCore.QRect(210, 270, 93, 28))
        self.addLocation.setObjectName("addLocation")
        self.addLocation.clicked.connect(self.addnewLocation)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Add a Location"))
        self.label_2.setText(_translate("Form", "Label"))
        self.label_3.setText(_translate("Form", "X-Coordinate"))
        self.label_4.setText(_translate("Form", "Y-Coordinate"))
        self.label_5.setText(_translate("Form", "Space"))
        self.addLocation.setText(_translate("Form", "Add Location"))

    def addnewLocation(self):
        if (len(self.LabelEntry.text()) > 0 and len(self.LabelEntry.text()) <= 40):
            cnx = mysql.connector.connect(user='root', password='(placeholder)',
                              host='127.0.0.1',
                              database='restaurant_supply_express', port=3306)
            cursor = cnx.cursor()
            cursor.callproc('add_location', [self.LabelEntry.text(), self.XCoordEntry.text(), self.YcoordEntry.text(), self.SpaceEntry.text()])
            cnx.commit()
            cnx.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Add_NewLocation()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
