# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import uic, QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QWidget, QLabel, QTableView, QTableWidgetItem)
from addOwner import Add_NewOwner
from employeeview import EmployeeView
from locationview import LocationView
from ingredientview import IngredientView
from serviceview import ServiceView
from ownerview import OwnerView
from addEmployee import Add_NewEmployee
from pilotview import PilotView
from AddPilot import Add_Pilot_Role
from AddService import Add_NewService
from AddDrone import Add_Drone
from AddWorker import Add_Worker_Role
from addLocation import Add_NewLocation
from addIngredient import Add_NewIngredient
from AddRestaurant import Add_Restaurant
from RemoveIngredient import Remove_Ingredient
from RemoveDrone import Remove_Drone
from RemovePilot import Remove_Pilot_Role
from StartFunding import Start_Funding
from HireEmployee import Hire_Employee
from FireEmployee import Fire_Employee
from ManageService import Manage_Service
from TakeoverDrone import Takeover_Drone
from JoinSwarm import Join_Swarm
from LeaveSwarm import Leave_Swarm
from LoadDrone import Load_Drone
from RefuelDrone import Refuel_Drone
from FlyDrone import Fly_Drone
from PurchaseIngredient import Purchase_Ingredient


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(824, 646)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(350, 10, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.newOwnerButton = QtWidgets.QPushButton(Form)
        self.newOwnerButton.setGeometry(QtCore.QRect(120, 100, 141, 28))
        self.newOwnerButton.setObjectName("newOwnerButton")
        self.EmployeeViewButton = QtWidgets.QPushButton(Form)
        self.EmployeeViewButton.setGeometry(QtCore.QRect(560, 130, 131, 28))
        self.EmployeeViewButton.setObjectName("EmployeeViewButton")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(140, 80, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(580, 80, 91, 16))
        self.label_3.setObjectName("label_3")
        self.OwnerViewButton = QtWidgets.QPushButton(Form)
        self.OwnerViewButton.setGeometry(QtCore.QRect(560, 100, 131, 28))
        self.OwnerViewButton.setObjectName("OwnerViewButton")
        self.PilotViewButton = QtWidgets.QPushButton(Form)
        self.PilotViewButton.setGeometry(QtCore.QRect(560, 160, 131, 28))
        self.PilotViewButton.setObjectName("PilotViewButton")
        self.LocationViewButton = QtWidgets.QPushButton(Form)
        self.LocationViewButton.setGeometry(QtCore.QRect(560, 190, 131, 28))
        self.LocationViewButton.setObjectName("LocationViewButton")
        self.IngredientViewButton = QtWidgets.QPushButton(Form)
        self.IngredientViewButton.setGeometry(QtCore.QRect(560, 220, 131, 28))
        self.IngredientViewButton.setObjectName("IngredientViewButton")
        self.ServiceViewButton = QtWidgets.QPushButton(Form)
        self.ServiceViewButton.setGeometry(QtCore.QRect(560, 250, 131, 28))
        self.ServiceViewButton.setObjectName("ServiceViewButton")
        self.newEmployeeButton = QtWidgets.QPushButton(Form)
        self.newEmployeeButton.setGeometry(QtCore.QRect(120, 130, 141, 28))
        self.newEmployeeButton.setObjectName("newEmployeeButton")
        self.newPilotButton = QtWidgets.QPushButton(Form)
        self.newPilotButton.setGeometry(QtCore.QRect(120, 160, 141, 28))
        self.newPilotButton.setObjectName("newPilotButton")
        self.newWorkerButton = QtWidgets.QPushButton(Form)
        self.newWorkerButton.setGeometry(QtCore.QRect(120, 190, 141, 28))
        self.newWorkerButton.setObjectName("newWorkerButton")
        self.newIngredientButton = QtWidgets.QPushButton(Form)
        self.newIngredientButton.setGeometry(QtCore.QRect(120, 220, 141, 28))
        self.newIngredientButton.setObjectName("newIngredientButton")
        self.newDroneButton = QtWidgets.QPushButton(Form)
        self.newDroneButton.setGeometry(QtCore.QRect(120, 250, 141, 28))
        self.newDroneButton.setObjectName("newDroneButton")
        self.newRestaurantButton = QtWidgets.QPushButton(Form)
        self.newRestaurantButton.setGeometry(QtCore.QRect(120, 280, 141, 28))
        self.newRestaurantButton.setObjectName("newRestaurantButton")
        self.newServiceButton = QtWidgets.QPushButton(Form)
        self.newServiceButton.setGeometry(QtCore.QRect(120, 310, 141, 28))
        self.newServiceButton.setObjectName("newServiceButton")
        self.newLocationButton = QtWidgets.QPushButton(Form)
        self.newLocationButton.setGeometry(QtCore.QRect(120, 340, 141, 28))
        self.newLocationButton.setObjectName("newLocationButton")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(350, 80, 131, 16))
        self.label_4.setObjectName("label_4")
        self.startFundingButton = QtWidgets.QPushButton(Form)
        self.startFundingButton.setGeometry(QtCore.QRect(350, 100, 131, 28))
        self.startFundingButton.setObjectName("startFundingButton")
        self.hireEmployeeButton = QtWidgets.QPushButton(Form)
        self.hireEmployeeButton.setGeometry(QtCore.QRect(350, 130, 131, 28))
        self.hireEmployeeButton.setObjectName("hireEmployeeButton")
        self.fireEmployeeButton = QtWidgets.QPushButton(Form)
        self.fireEmployeeButton.setGeometry(QtCore.QRect(350, 160, 131, 28))
        self.fireEmployeeButton.setObjectName("fireEmployeeButton")
        self.manageServiceButton = QtWidgets.QPushButton(Form)
        self.manageServiceButton.setGeometry(QtCore.QRect(350, 190, 131, 28))
        self.manageServiceButton.setObjectName("manageServiceButton")
        self.takeoverDroneButton = QtWidgets.QPushButton(Form)
        self.takeoverDroneButton.setGeometry(QtCore.QRect(350, 220, 131, 28))
        self.takeoverDroneButton.setObjectName("takeoverDroneButton")
        self.joinSwarmButton = QtWidgets.QPushButton(Form)
        self.joinSwarmButton.setGeometry(QtCore.QRect(350, 250, 131, 28))
        self.joinSwarmButton.setObjectName("joinSwarmButton")
        self.leaveSwarmButton = QtWidgets.QPushButton(Form)
        self.leaveSwarmButton.setGeometry(QtCore.QRect(350, 280, 131, 28))
        self.leaveSwarmButton.setObjectName("leaveSwarmButton")
        self.loadDroneButton = QtWidgets.QPushButton(Form)
        self.loadDroneButton.setGeometry(QtCore.QRect(350, 310, 131, 28))
        self.loadDroneButton.setObjectName("loadDroneButton")
        self.refuelDroneButton = QtWidgets.QPushButton(Form)
        self.refuelDroneButton.setGeometry(QtCore.QRect(350, 340, 131, 28))
        self.refuelDroneButton.setObjectName("refuelDroneButton")
        self.flyDroneButton = QtWidgets.QPushButton(Form)
        self.flyDroneButton.setGeometry(QtCore.QRect(350, 370, 131, 28))
        self.flyDroneButton.setObjectName("flyDroneButton")
        self.purchaseIngredientButton = QtWidgets.QPushButton(Form)
        self.purchaseIngredientButton.setGeometry(QtCore.QRect(350, 400, 131, 28))
        self.purchaseIngredientButton.setObjectName("purchaseIngredientButton")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(120, 400, 141, 16))
        self.label_5.setObjectName("label_5")
        self.removeIngredientButton = QtWidgets.QPushButton(Form)
        self.removeIngredientButton.setGeometry(QtCore.QRect(120, 420, 141, 28))
        self.removeIngredientButton.setObjectName("removeIngredientButton")
        self.removePilotButton = QtWidgets.QPushButton(Form)
        self.removePilotButton.setGeometry(QtCore.QRect(120, 480, 141, 28))
        self.removePilotButton.setObjectName("removePilotButton")
        self.removeDroneButton = QtWidgets.QPushButton(Form)
        self.removeDroneButton.setGeometry(QtCore.QRect(120, 450, 141, 28))
        self.removeDroneButton.setObjectName("removeDroneButton")
        self.EmployeeViewButton.clicked.connect(self.employeeView)
        self.newOwnerButton.clicked.connect(self.addNewOwnerView)
        self.newEmployeeButton.clicked.connect(self.addNewEmployeeView)
        self.LocationViewButton.clicked.connect(self.locationView)
        self.IngredientViewButton.clicked.connect(self.ingredientView)
        self.PilotViewButton.clicked.connect(self.pilotView)
        self.ServiceViewButton.clicked.connect(self.serviceView)
        self.OwnerViewButton.clicked.connect(self.ownerView)
        self.newDroneButton.clicked.connect(self.addDrone)
        self.newPilotButton.clicked.connect(self.addPilot)
        self.newIngredientButton.clicked.connect(self.addIngredient)
        self.newServiceButton.clicked.connect(self.addService)
        self.newWorkerButton.clicked.connect(self.addWorker)
        self.newLocationButton.clicked.connect(self.addLocation)
        self.newRestaurantButton.clicked.connect(self.addRestaurant)
        self.removeDroneButton.clicked.connect(self.removeDrone)
        self.removeIngredientButton.clicked.connect(self.removeIngredient)
        self.removePilotButton.clicked.connect(self.removePilot)
        self.startFundingButton.clicked.connect(self.startFunding)
        self.hireEmployeeButton.clicked.connect(self.hireEmployee)
        self.fireEmployeeButton.clicked.connect(self.fireEmployee)
        self.manageServiceButton.clicked.connect(self.manageService)
        self.takeoverDroneButton.clicked.connect(self.takeoverDrone)
        self.joinSwarmButton.clicked.connect(self.joinSwarm)
        self.leaveSwarmButton.clicked.connect(self.leaveSwarm)
        self.loadDroneButton.clicked.connect(self.loadDrone)
        self.refuelDroneButton.clicked.connect(self.refuelDrone)
        self.flyDroneButton.clicked.connect(self.flyDrone)
        self.purchaseIngredientButton.clicked.connect(self.purchaseIngredient)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Home Page"))
        self.newOwnerButton.setText(_translate("Form", "Add New Owner"))
        self.EmployeeViewButton.setText(_translate("Form", "Employee View"))
        self.label_2.setText(_translate("Form", "Add to Database"))
        self.label_3.setText(_translate("Form", "Database Views"))
        self.OwnerViewButton.setText(_translate("Form", "Owner View"))
        self.PilotViewButton.setText(_translate("Form", "Pilot View"))
        self.LocationViewButton.setText(_translate("Form", "Location View"))
        self.IngredientViewButton.setText(_translate("Form", "Ingredient View"))
        self.ServiceViewButton.setText(_translate("Form", "Service View"))
        self.newEmployeeButton.setText(_translate("Form", "Add New Employee"))
        self.newPilotButton.setText(_translate("Form", "Add Pilot Role"))
        self.newWorkerButton.setText(_translate("Form", "Add Worker Role"))
        self.newIngredientButton.setText(_translate("Form", "Add Ingredient"))
        self.newDroneButton.setText(_translate("Form", "Add Drone"))
        self.newRestaurantButton.setText(_translate("Form", "Add Restaurant"))
        self.newServiceButton.setText(_translate("Form", "Add Service"))
        self.newLocationButton.setText(_translate("Form", "Add Location"))
        self.label_4.setText(_translate("Form", "Database Modification"))
        self.startFundingButton.setText(_translate("Form", "Start Funding"))
        self.hireEmployeeButton.setText(_translate("Form", "Hire Employee"))
        self.fireEmployeeButton.setText(_translate("Form", "Fire Employee"))
        self.manageServiceButton.setText(_translate("Form", "Manage Service"))
        self.takeoverDroneButton.setText(_translate("Form", "Take Over Drone"))
        self.joinSwarmButton.setText(_translate("Form", "Join Swarm"))
        self.leaveSwarmButton.setText(_translate("Form", "Leave Swarm"))
        self.loadDroneButton.setText(_translate("Form", "Load Drone"))
        self.refuelDroneButton.setText(_translate("Form", "Refuel Drone"))
        self.flyDroneButton.setText(_translate("Form", "Fly Drone"))
        self.purchaseIngredientButton.setText(_translate("Form", "Purchase Ingredient"))
        self.label_5.setText(_translate("Form", "Remove from Database"))
        self.removeIngredientButton.setText(_translate("Form", "Remove Ingredient"))
        self.removePilotButton.setText(_translate("Form", "Remove Pilot Role"))
        self.removeDroneButton.setText(_translate("Form", "Remove Drone"))
        


    def addNewOwnerView(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Add_NewOwner()
        self.ui.setupUi(self.window)
        self.window.show()

    def employeeView(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = EmployeeView()
        self.ui.setupUi(self.window)
        self.window.show()

    def addNewEmployeeView(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Add_NewEmployee()
        self.ui.setupUi(self.window)
        self.window.show()

    def pilotView(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = PilotView()
        self.ui.setupUi(self.window)
        self.window.show()

    def serviceView(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = ServiceView()
        self.ui.setupUi(self.window)
        self.window.show()

    def ingredientView(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = IngredientView()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def ownerView(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = OwnerView()
        self.ui.setupUi(self.window)
        self.window.show()

    def locationView(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = LocationView()
        self.ui.setupUi(self.window)
        self.window.show()

    def addPilot(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Add_Pilot_Role()
        self.ui.setupUi(self.window)
        self.window.show()

    def addService(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Add_NewService()
        self.ui.setupUi(self.window)
        self.window.show()

    def addDrone(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Add_Drone()
        self.ui.setupUi(self.window)
        self.window.show()

    def addWorker(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Add_Worker_Role()
        self.ui.setupUi(self.window)
        self.window.show()

    def addLocation(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Add_NewLocation()
        self.ui.setupUi(self.window)
        self.window.show()

    def addIngredient(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Add_NewIngredient()
        self.ui.setupUi(self.window)
        self.window.show()

    def addRestaurant(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Add_Restaurant()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def removePilot(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Remove_Pilot_Role()
        self.ui.setupUi(self.window)
        self.window.show()

    def removeDrone(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Remove_Drone()
        self.ui.setupUi(self.window)
        self.window.show()

    def removeIngredient(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Remove_Ingredient()
        self.ui.setupUi(self.window)
        self.window.show()

    def startFunding(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Start_Funding()
        self.ui.setupUi(self.window)
        self.window.show()

    def hireEmployee(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Hire_Employee()
        self.ui.setupUi(self.window)
        self.window.show()

    def fireEmployee(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Fire_Employee()
        self.ui.setupUi(self.window)
        self.window.show()

    def manageService(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Manage_Service()
        self.ui.setupUi(self.window)
        self.window.show()

    def takeoverDrone(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Takeover_Drone()
        self.ui.setupUi(self.window)
        self.window.show()

    def joinSwarm(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Join_Swarm()
        self.ui.setupUi(self.window)
        self.window.show()

    def leaveSwarm(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Leave_Swarm()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def loadDrone(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Load_Drone()
        self.ui.setupUi(self.window)
        self.window.show()

    def refuelDrone(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Refuel_Drone()
        self.ui.setupUi(self.window)
        self.window.show()

    def flyDrone(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Fly_Drone()
        self.ui.setupUi(self.window)
        self.window.show()

    def purchaseIngredient(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Purchase_Ingredient()
        self.ui.setupUi(self.window)
        self.window.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
