# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PurchaseIngredient.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import uic, QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator
from PyQt5.QtWidgets import (QApplication, QWidget, QLabel, QTableView, QTableWidgetItem)
import mysql.connector

class Purchase_Ingredient(object):
    def setupRestaurants(self):
        cnx = mysql.connector.connect(user='root', password='(placeholder)',
                              host='127.0.0.1',
                              database='restaurant_supply_express', port=3306)
        mycursor = cnx.cursor()
        mycursor.execute("select long_name from restaurants;")
        myresult = mycursor.fetchall()
        for row_data in myresult:
            for data in row_data:
                self.RestaurantName.addItem(data)
        cnx.close()
    def setupDroneID(self):
        cnx = mysql.connector.connect(user='root', password='Fl1ght413612!',
                              host='127.0.0.1',
                              database='restaurant_supply_express', port=3306)
        mycursor = cnx.cursor()
        mycursor.execute("select distinct id from drones where hover = (select location from restaurants where long_name = \'"+ self.RestaurantName.currentText() + "\');")
        myresult = mycursor.fetchall()
        for row_data in myresult:
            for data in row_data:
                self.DroneID.addItem(data)
        cnx.close()

    def setupDroneTag(self):
        cnx = mysql.connector.connect(user='root', password='Fl1ght413612!',
                              host='127.0.0.1',
                              database='restaurant_supply_express', port=3306)
        mycursor = cnx.cursor()
        mycursor.execute("select tag from drones where id = \'"+ self.DroneID.currentText() + "\' and hover = (select location from restaurants where long_name = \'"+ self.RestaurantName.currentText() + "\')")
        myresult = mycursor.fetchall()
        for row_data in myresult:
            for data in row_data:
                self.DroneTag.addItem(str(data))
        cnx.close()

    def setupBarcode(self):
        cnx = mysql.connector.connect(user='root', password='Fl1ght413612!',
                              host='127.0.0.1',
                              database='restaurant_supply_express', port=3306)
        mycursor = cnx.cursor()
        mycursor.execute("select barcode from payload where id = \'"+ self.DroneID.currentText() + "\' and tag =  \'"+ self.DroneTag.currentText() + "\'")
        myresult = mycursor.fetchall()
        for row_data in myresult:
            for data in row_data:
                self.Barcode.addItem(data)
        cnx.close()
        mycursor.close()
        
    def quantityChange(self):
        cnx = mysql.connector.connect(user='root', password='Fl1ght413612!',
                              host='127.0.0.1',
                              database='restaurant_supply_express', port=3306)
        mycursor = cnx.cursor()
        mycursor.execute("select quantity from payload where id = \'"+ self.DroneID.currentText() + "\' and tag =  \'"+ self.DroneTag.currentText() + "\' and barcode = \'"+ self.Barcode.currentText() + "\'")
        myresult = mycursor.fetchall()
        for row_data in myresult:
            for data in row_data:
                if (data == ""):
                    data = 0
                self.QuantityLabel.setText("Quantity of Ingredient Available: " + str(data))
        cnx.close()
        mycursor.close()

    def RestaurantChange(self):
        self.DroneID.clear()
        self.setupDroneID()
        self.DroneTag.clear()
        self.setupDroneTag()
        self.Barcode.clear()
        self.setupBarcode()
        self.quantityChange()

    def DroneIDChange(self):
        self.DroneTag.clear()
        self.setupDroneTag()
        self.Barcode.clear()
        self.setupBarcode()
        self.quantityChange()
        
    def DroneTagChange(self):
        self.Barcode.clear()
        self.setupBarcode()
        self.quantityChange()

    def BarcodeChange(self):
        self.quantityChange()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(576, 483)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(160, -30, 261, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 220, 81, 51))
        self.label_6.setObjectName("label_6")
        self.flyDroneButton = QtWidgets.QPushButton(Form)
        self.flyDroneButton.setGeometry(QtCore.QRect(220, 420, 131, 28))
        self.flyDroneButton.setObjectName("flyDroneButton")
        self.Barcode = QtWidgets.QComboBox(Form)
        self.Barcode.setGeometry(QtCore.QRect(100, 240, 401, 22))
        self.Barcode.setObjectName("Barcode")
        self.DroneID = QtWidgets.QComboBox(Form)
        self.DroneID.setGeometry(QtCore.QRect(100, 130, 401, 22))
        self.DroneID.setObjectName("DroneID")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 190, 61, 16))
        self.label_4.setObjectName("label_4")
        self.DroneTag = QtWidgets.QComboBox(Form)
        self.DroneTag.setGeometry(QtCore.QRect(100, 190, 401, 22))
        self.DroneTag.setObjectName("DroneTag")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(30, 60, 81, 61))
        self.label_7.setObjectName("label_7")
        self.RestaurantName = QtWidgets.QComboBox(Form)
        self.RestaurantName.setGeometry(QtCore.QRect(100, 80, 401, 22))
        self.RestaurantName.setObjectName("RestaurantName")
        self.QuantityEntry = QtWidgets.QLineEdit(Form)
        self.QuantityEntry.setGeometry(QtCore.QRect(100, 290, 401, 22))
        self.QuantityEntry.setObjectName("QuantityEntry")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 280, 55, 41))
        self.label_3.setObjectName("label_3")
        self.QuantityLabel = QtWidgets.QLabel(Form)
        self.QuantityLabel.setGeometry(QtCore.QRect(30, 330, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.QuantityLabel.setFont(font)
        self.QuantityLabel.setObjectName("QuantityLabel")
        self.setupRestaurants()
        self.setupDroneID()
        self.setupDroneTag()
        self.setupBarcode()
        self.quantityChange()
        self.RestaurantName.currentIndexChanged.connect(self.RestaurantChange)
        self.DroneID.currentIndexChanged.connect(self.DroneIDChange)
        self.DroneTag.currentIndexChanged.connect(self.DroneTagChange)
        self.Barcode.currentIndexChanged.connect(self.BarcodeChange)
        self.QuantityEntry.setValidator(QIntValidator())
        self.flyDroneButton.clicked.connect(self.purchaseIngredient)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Purchase Ingredient"))
        self.label_6.setText(_translate("Form", "Ingredient\n"
"Barcode"))
        self.flyDroneButton.setText(_translate("Form", "Purchase Ingredient"))
        self.label_2.setText(_translate("Form", "Drone ID"))
        self.label_4.setText(_translate("Form", "Drone Tag"))
        self.label_7.setText(_translate("Form", "Restaurant\n"
"Name"))
        self.label_3.setText(_translate("Form", "Quantity\n"
"to Buy"))
        self.QuantityLabel.setText(_translate("Form", "Quantity of Ingredient Available:"))

    def purchaseIngredient(self):
        if (len(self.Barcode.currentText()) > 0  and len(self.QuantityEntry.text()) > 0):
            cnx = mysql.connector.connect(user='root', password='Fl1ght413612!',
                      host='127.0.0.1',
                      database='restaurant_supply_express', port=3306)
            cursor = cnx.cursor()
            cursor.callproc('purchase_ingredient', [self.RestaurantName.currentText(), self.DroneID.currentText(), self.DroneTag.currentText(), self.Barcode.currentText(), self.QuantityEntry.text()])
            cnx.commit()
            cnx.close()
            self.DroneTagChange()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Purchase_Ingredient()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
