# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addIngredient.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import uic, QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator
from PyQt5.QtWidgets import (QApplication, QWidget, QLabel, QTableView, QTableWidgetItem)
import mysql.connector 

class Add_NewIngredient(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(541, 282)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(160, -40, 221, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.BarcodeEntry = QtWidgets.QLineEdit(Form)
        self.BarcodeEntry.setGeometry(QtCore.QRect(100, 90, 401, 22))
        self.BarcodeEntry.setObjectName("BarcodeEntry")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 61, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 71, 31))
        self.label_3.setObjectName("label_3")
        self.iNameEntry = QtWidgets.QLineEdit(Form)
        self.iNameEntry.setGeometry(QtCore.QRect(100, 130, 401, 22))
        self.iNameEntry.setObjectName("iNameEntry")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 61, 21))
        self.label_4.setObjectName("label_4")
        self.WeightEntry = QtWidgets.QLineEdit(Form)
        self.WeightEntry.setGeometry(QtCore.QRect(100, 170, 401, 22))
        self.WeightEntry.setObjectName("WeightEntry")
        self.WeightEntry.setValidator(QIntValidator())
        self.addIngredient = QtWidgets.QPushButton(Form)
        self.addIngredient.setGeometry(QtCore.QRect(210, 230, 111, 28))
        self.addIngredient.setObjectName("addIngredient")
        self.addIngredient.clicked.connect(self.addnewIngredient)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Add an Ingredient"))
        self.label_2.setText(_translate("Form", "Barcode"))
        self.label_3.setText(_translate("Form", "Ingredient \n"
" Name"))
        self.label_4.setText(_translate("Form", "Weight"))
        self.addIngredient.setText(_translate("Form", "Add Ingredient"))

    def addnewIngredient(self):
        
        if (len(self.BarcodeEntry.text()) > 0 and len(self.BarcodeEntry.text()) <= 40 and len(self.iNameEntry.text()) > 0 and len(self.iNameEntry.text()) <= 100):
            cnx = mysql.connector.connect(user='root', password='(placeholder)',
                              host='127.0.0.1',
                              database='restaurant_supply_express', port=3306)
            cursor = cnx.cursor()
            cursor.callproc('add_ingredient', [self.BarcodeEntry.text(), self.iNameEntry.text(), self.WeightEntry.text()])
            cnx.commit()
            cnx.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Add_NewIngredient()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
