# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addOwner.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import uic, QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QWidget, QLabel, QTableView, QTableWidgetItem)
import mysql.connector 


class Add_NewOwner(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(532, 468)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, -40, 181, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.UsernameEntry = QtWidgets.QLineEdit(Form)
        self.UsernameEntry.setGeometry(QtCore.QRect(100, 90, 401, 22))
        self.UsernameEntry.setObjectName("UsernameEntry")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 61, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 71, 21))
        self.label_3.setObjectName("label_3")
        self.FirstNameEntry = QtWidgets.QLineEdit(Form)
        self.FirstNameEntry.setGeometry(QtCore.QRect(100, 130, 401, 22))
        self.FirstNameEntry.setObjectName("FirstNameEntry")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 61, 21))
        self.label_4.setObjectName("label_4")
        self.LastNameEntry = QtWidgets.QLineEdit(Form)
        self.LastNameEntry.setGeometry(QtCore.QRect(100, 170, 401, 22))
        self.LastNameEntry.setObjectName("LastNameEntry")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 220, 61, 21))
        self.label_5.setObjectName("label_5")
        self.AddressEntry = QtWidgets.QLineEdit(Form)
        self.AddressEntry.setGeometry(QtCore.QRect(100, 220, 401, 22))
        self.AddressEntry.setObjectName("AddressEntry")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 280, 61, 21))
        self.label_6.setObjectName("label_6")
        self.DateEntry = QtWidgets.QDateEdit(Form)
        self.DateEntry.setGeometry(QtCore.QRect(100, 280, 401, 22))
        self.DateEntry.setObjectName("DateEntry")
        self.DateEntry.setCalendarPopup(True)
        self.addOwner = QtWidgets.QPushButton(Form)
        self.addOwner.setGeometry(QtCore.QRect(210, 360, 93, 28))
        self.addOwner.clicked.connect(self.addnewOwner)
        self.addOwner.setObjectName("addOwner")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Add an Owner"))
        self.label_2.setText(_translate("Form", "Username"))
        self.label_3.setText(_translate("Form", "First Name"))
        self.label_4.setText(_translate("Form", "Last Name"))
        self.label_5.setText(_translate("Form", "Address"))
        self.label_6.setText(_translate("Form", "Birth Date"))
        self.DateEntry.setDisplayFormat(_translate("Form", "yyyy-MM-dd"))
        self.addOwner.setText(_translate("Form", "Add Owner"))


    def addnewOwner(self):
        if (len(self.UsernameEntry.text()) > 0 and len(self.UsernameEntry.text()) <= 40 and len(self.FirstNameEntry.text()) > 0 and len(self.FirstNameEntry.text()) <= 100 and len(self.LastNameEntry.text()) > 0 and len(self.LastNameEntry.text()) <= 100 and len(self.AddressEntry.text()) > 0 and len(self.AddressEntry.text()) <= 500):
            cnx = mysql.connector.connect(user='root', password='(placeholder)',
                              host='127.0.0.1',
                              database='restaurant_supply_express', port=3306)
            cursor = cnx.cursor()
            cursor.callproc('add_owner', [self.UsernameEntry.text(), self.FirstNameEntry.text(), self.LastNameEntry.text(), self.AddressEntry.text(), self.DateEntry.text()])
            cnx.commit()
            cnx.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Add_NewOwner()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
