# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddPilot.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import uic, QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator
from PyQt5.QtWidgets import (QApplication, QWidget, QLabel, QTableView, QTableWidgetItem)
import mysql.connector

class Add_Pilot_Role(object):
    def setupDropDown(self):
        cnx = mysql.connector.connect(user='root', password='(placeholder)',
                              host='127.0.0.1',
                              database='restaurant_supply_express', port=3306)
        mycursor = cnx.cursor()
        mycursor.execute("select username from employees where username not in (select username from pilots);")
        myresult = mycursor.fetchall()
        for row_data in myresult:
            for data in row_data:
                self.PilotUsername.addItem(data)
        cnx.close

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(541, 289)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, -30, 181, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 71, 21))
        self.label_3.setObjectName("label_3")
        self.LicenseIDEntry = QtWidgets.QLineEdit(Form)
        self.LicenseIDEntry.setGeometry(QtCore.QRect(100, 130, 401, 22))
        self.LicenseIDEntry.setText("")
        self.LicenseIDEntry.setObjectName("LicenseIDEntry")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 170, 71, 31))
        self.label_5.setObjectName("label_5")
        self.ExperienceEntry = QtWidgets.QLineEdit(Form)
        self.ExperienceEntry.setGeometry(QtCore.QRect(100, 180, 401, 22))
        self.ExperienceEntry.setObjectName("ExperienceEntry")
        self.ExperienceEntry.setValidator(QIntValidator())
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 80, 61, 31))
        self.label_6.setObjectName("label_6")
        self.addPilot = QtWidgets.QPushButton(Form)
        self.addPilot.setGeometry(QtCore.QRect(220, 240, 93, 28))
        self.addPilot.setObjectName("addPilot")
        self.PilotUsername = QtWidgets.QComboBox(Form)
        self.PilotUsername.setGeometry(QtCore.QRect(100, 80, 401, 22))
        self.PilotUsername.setObjectName("PilotUsername")
        self.addPilot.clicked.connect(self.addnewPilot)
        self.setupDropDown()
        

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Add a Pilot"))
        self.label_3.setText(_translate("Form", "License ID"))
        self.label_5.setText(_translate("Form", "Pilot \n"
"Experience"))
        self.label_6.setText(_translate("Form", "Pilot \n"
"Username"))
        self.addPilot.setText(_translate("Form", "Add Pilot"))

    def addnewPilot(self):
        if (len(self.LicenseIDEntry.text()) > 0 and len(self.LicenseIDEntry.text()) <= 40 and len(self.ExperienceEntry.text()) > 0):
            cnx = mysql.connector.connect(user='root', password='Fl1ght413612!',
                              host='127.0.0.1',
                              database='restaurant_supply_express', port=3306)
            cursor = cnx.cursor()
            cursor.callproc('add_pilot_role', [self.PilotUsername.currentText(), self.LicenseIDEntry.text(), self.ExperienceEntry.text()])
            cnx.commit()
            cnx.close()
            self.PilotUsername.clear()
            self.setupDropDown()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Add_Pilot_Role()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
