# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddService.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import uic, QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QWidget, QLabel, QTableView, QTableWidgetItem)
import mysql.connector

class Add_NewService(object):
    def setupManager(self):
        cnx = mysql.connector.connect(user='root', password='(placeholder)',
                              host='127.0.0.1',
                              database='restaurant_supply_express', port=3306)
        mycursor = cnx.cursor()
        mycursor.execute("select username from workers")
        myresult = mycursor.fetchall()
        for row_data in myresult:
            for data in row_data:
                self.ManagerUsername.addItem(data)
        cnx.close
    
    def setupHomeBase(self):
        cnx = mysql.connector.connect(user='root', password='Fl1ght413612!',
                              host='127.0.0.1',
                              database='restaurant_supply_express', port=3306)
        mycursor = cnx.cursor()
        mycursor.execute("select label from locations")
        myresult = mycursor.fetchall()
        for row_data in myresult:
            for data in row_data:
                self.HomeBase.addItem(data)
        cnx.close
    
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(576, 469)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(200, -40, 181, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 170, 71, 21))
        self.label_3.setObjectName("label_3")
        self.NameEntry = QtWidgets.QLineEdit(Form)
        self.NameEntry.setGeometry(QtCore.QRect(90, 170, 401, 22))
        self.NameEntry.setText("")
        self.NameEntry.setObjectName("NameEntry")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 71, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 260, 61, 31))
        self.label_6.setObjectName("label_6")
        self.addService = QtWidgets.QPushButton(Form)
        self.addService.setGeometry(QtCore.QRect(230, 380, 93, 28))
        self.addService.setObjectName("addService")
        self.ManagerUsername = QtWidgets.QComboBox(Form)
        self.ManagerUsername.setGeometry(QtCore.QRect(90, 270, 401, 22))
        self.ManagerUsername.setObjectName("ManagerUsername")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 61, 16))
        self.label_4.setObjectName("label_4")
        self.IDEntry = QtWidgets.QLineEdit(Form)
        self.IDEntry.setGeometry(QtCore.QRect(90, 120, 401, 22))
        self.IDEntry.setObjectName("IDEntry")
        self.HomeBase = QtWidgets.QComboBox(Form)
        self.HomeBase.setGeometry(QtCore.QRect(90, 220, 401, 22))
        self.HomeBase.setObjectName("HomeBase")
        self.setupManager()
        self.setupHomeBase()
        self.addService.clicked.connect(self.addnewService)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Add a Service"))
        self.label_3.setText(_translate("Form", "Name"))
        self.label_5.setText(_translate("Form", "Home Base"))
        self.label_6.setText(_translate("Form", "Manager \n"
"Username"))
        self.addService.setText(_translate("Form", "Add Service"))
        self.label_4.setText(_translate("Form", "ID"))

    def addnewService(self):
        if (len(self.IDEntry.text()) > 0 and len(self.IDEntry.text()) <= 40 and len(self.NameEntry.text()) > 0 and len(self.NameEntry.text()) <= 100):
            cnx = mysql.connector.connect(user='root', password='Fl1ght413612!',
                          host='127.0.0.1',
                          database='restaurant_supply_express', port=3306)
            cursor = cnx.cursor()
            cursor.callproc('add_service', [self.IDEntry.text(), self.NameEntry.text(), self.HomeBase.currentText(), self.ManagerUsername.currentText()])
            cnx.commit()
            cnx.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Add_NewService()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
