# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoadDrone.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import uic, QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator
from PyQt5.QtWidgets import (QApplication, QWidget, QLabel, QTableView, QTableWidgetItem)
import mysql.connector

class Load_Drone(object):
    def setupDroneID(self):
        cnx = mysql.connector.connect(user='root', password='(placeholder)',
                              host='127.0.0.1',
                              database='restaurant_supply_express', port=3306)
        mycursor = cnx.cursor()
        mycursor.execute("select distinct id from drones;")
        myresult = mycursor.fetchall()
        for row_data in myresult:
            for data in row_data:
                self.DroneID.addItem(data)
        cnx.close()
        mycursor.close()

    def setupDroneTag(self):
        cnx = mysql.connector.connect(user='root', password='Fl1ght413612!',
                              host='127.0.0.1',
                              database='restaurant_supply_express', port=3306)
        mycursor = cnx.cursor()
        mycursor.execute("select tag from drones where id = \'"+ self.DroneID.currentText() + "\'")
        myresult = mycursor.fetchall()
        for row_data in myresult:
            for data in row_data:
                self.DroneTag.addItem(str(data))
        cnx.close()
        mycursor.close()

    def setupBarcode(self):
        cnx = mysql.connector.connect(user='root', password='Fl1ght413612!',
                              host='127.0.0.1',
                              database='restaurant_supply_express', port=3306)
        mycursor = cnx.cursor()
        mycursor.execute("select barcode from ingredients")
        myresult = mycursor.fetchall()
        for row_data in myresult:
            for data in row_data:
                self.Barcode.addItem(data)
        cnx.close()
        mycursor.close()
        
    def setupCapacity(self):
        cnx = mysql.connector.connect(user='root', password='Fl1ght413612!',
                              host='127.0.0.1',
                              database='restaurant_supply_express', port=3306)
        mycursor = cnx.cursor()
        mycursor.execute("select capacity from drones where (id = \'"+ self.DroneID.currentText() + "\' and tag = \'"+ self.DroneTag.currentText() + "\')")
        myresult1 = mycursor.fetchall()
        mycursor.execute("select sum(quantity) from payload where id = \'"+ self.DroneID.currentText() + "\' and tag = \'"+ self.DroneTag.currentText() + "\'")
        myresult2 = mycursor.fetchall()
        for row_data in myresult1:
            for data in row_data:
                hold1 = int(data)
        for row_data in myresult2:
            for data in row_data:
                if data is None:
                    data = 0
                hold2 = int(data)
        self.label_7.setText("Drone Capacity Remaining: " + str(hold1 - hold2))
        cnx.close()
        mycursor.close()

    def DroneIDChange(self):
        self.DroneTag.clear()
        self.setupDroneTag()
        self.setupCapacity()

    def DroneTagChange(self):
        self.setupCapacity()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(576, 491)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(210, -30, 261, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 220, 81, 51))
        self.label_6.setObjectName("label_6")
        self.loadDroneButton = QtWidgets.QPushButton(Form)
        self.loadDroneButton.setGeometry(QtCore.QRect(220, 430, 121, 28))
        self.loadDroneButton.setObjectName("loadDroneButton")
        self.Barcode = QtWidgets.QComboBox(Form)
        self.Barcode.setGeometry(QtCore.QRect(90, 240, 401, 22))
        self.Barcode.setObjectName("Barcode")
        self.DroneID = QtWidgets.QComboBox(Form)
        self.DroneID.setGeometry(QtCore.QRect(90, 70, 401, 22))
        self.DroneID.setObjectName("DroneID")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 61, 16))
        self.label_4.setObjectName("label_4")
        self.DroneTag = QtWidgets.QComboBox(Form)
        self.DroneTag.setGeometry(QtCore.QRect(90, 130, 401, 22))
        self.DroneTag.setObjectName("DroneTag")
        self.QuantityEntry = QtWidgets.QLineEdit(Form)
        self.QuantityEntry.setGeometry(QtCore.QRect(90, 300, 401, 22))
        self.QuantityEntry.setObjectName("QuantityEntry")
        self.PriceEntry = QtWidgets.QLineEdit(Form)
        self.PriceEntry.setGeometry(QtCore.QRect(90, 350, 401, 22))
        self.PriceEntry.setObjectName("PriceEntry")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 290, 81, 41))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 350, 55, 16))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(20, 180, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.QuantityEntry.setValidator(QIntValidator())
        self.PriceEntry.setValidator(QIntValidator())
        self.setupDroneID()
        self.setupDroneTag()
        self.setupBarcode()
        self.setupCapacity()
        self.DroneID.currentIndexChanged.connect(self.DroneIDChange)
        self.DroneTag.activated.connect(self.DroneTagChange)
        self.loadDroneButton.clicked.connect(self.loadDrone)
        

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Load Drone"))
        self.label_6.setText(_translate("Form", "Ingredient\n"
"Barcode"))
        self.loadDroneButton.setText(_translate("Form", "Load Drone"))
        self.label_2.setText(_translate("Form", "Drone ID"))
        self.label_4.setText(_translate("Form", "Drone Tag"))
        self.label_3.setText(_translate("Form", "# of\n"
"packages"))
        self.label_5.setText(_translate("Form", "Price"))
        self.label_7.setText(_translate("Form", "Drone Capacity Remaining:"))

    def loadDrone(self):
        if (len(self.QuantityEntry.text()) > 0 and len(self.PriceEntry.text()) > 0):
            cnx = mysql.connector.connect(user='root', password='Fl1ght413612!',
                          host='127.0.0.1',
                          database='restaurant_supply_express', port=3306)
            cursor = cnx.cursor()
            cursor.callproc('load_drone', [self.DroneID.currentText(), self.DroneTag.currentText(), self.Barcode.currentText(), self.QuantityEntry.text(), self.PriceEntry.text()])
            cnx.commit()
            cnx.close()
            self.DroneTagChange()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Load_Drone()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
