# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ManageService.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import uic, QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QWidget, QLabel, QTableView, QTableWidgetItem)
import mysql.connector

class Manage_Service(object):
    def setupService(self):
        cnx = mysql.connector.connect(user='root', password='(placeholder)',
                              host='127.0.0.1',
                              database='restaurant_supply_express', port=3306)
        mycursor = cnx.cursor()
        mycursor.execute("select id from delivery_services")
        myresult = mycursor.fetchall()
        for row_data in myresult:
            for data in row_data:
                self.ServiceID.addItem(data)
        cnx.close
        
    def setupEmployee(self):
        cnx = mysql.connector.connect(user='root', password='Fl1ght413612!',
                              host='127.0.0.1',
                              database='restaurant_supply_express', port=3306)
        mycursor = cnx.cursor()
        mycursor.execute("select username from work_for where (username not in (select flown_by from drones where flown_by is not null) and username not in (select manager from delivery_services) and id = \'" + self.ServiceID.currentText() +"\' and username not in (select username from work_for where id != \'" + self.ServiceID.currentText() +"\'))")
        myresult = mycursor.fetchall()
        for row_data in myresult:
            for data in row_data:
                self.EmployeeUsername.addItem(data)
        cnx.close

    def changeEmployee(self):
        self.EmployeeUsername.clear()
        self.setupEmployee()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(576, 332)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(200, -20, 321, 151))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ManageService = QtWidgets.QPushButton(Form)
        self.ManageService.setGeometry(QtCore.QRect(190, 240, 191, 28))
        self.ManageService.setObjectName("ManageService")
        self.EmployeeUsername = QtWidgets.QComboBox(Form)
        self.EmployeeUsername.setGeometry(QtCore.QRect(100, 160, 401, 22))
        self.EmployeeUsername.setObjectName("EmployeeUsername")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 160, 81, 31))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 71, 41))
        self.label_4.setObjectName("label_4")
        self.ServiceID = QtWidgets.QComboBox(Form)
        self.ServiceID.setGeometry(QtCore.QRect(100, 100, 401, 22))
        self.ServiceID.setObjectName("ServiceID")
        self.setupService()
        self.setupEmployee()
        self.ServiceID.currentIndexChanged.connect(self.changeEmployee)
        self.ManageService.clicked.connect(self.changeManager)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Change Manager"))
        self.ManageService.setText(_translate("Form", "Change Manager"))
        self.label_2.setText(_translate("Form", "Username of\n"
"Employee"))
        self.label_4.setText(_translate("Form", "ID of\n"
"Service"))

    def changeManager(self):
        cnx = mysql.connector.connect(user='root', password='Fl1ght413612!',
                      host='127.0.0.1',
                      database='restaurant_supply_express', port=3306)
        cursor = cnx.cursor()
        cursor.callproc('manage_service', [self.EmployeeUsername.currentText(), self.ServiceID.currentText()])
        cnx.commit()
        cnx.close()
        self.changeEmployee()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Manage_Service()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
